version: "3.9"

services:
  web:
    container_name: tarkovpedia
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.web
    ports:
      - "3000:3000"
    environment:
      HOST: "0.0.0.0"
      PORT: "3000"
      DATABASE_URL: "file:./database/tarkovpedia.db"
    volumes:
      - tarkovpedia_db:/app/database
    restart: unless-stopped

volumes:
  tarkovpedia_db:
    driver: local
